#! /bin/sh

## Autostart

# xhost (xserver no ditrobox)
# xhost +si:localuser:$USER

# xmodmap
xmodmap .Xmodmap

# Bar
$HOME/.config/polybar/launch.sh &

# Background
$HOME/.fehbg

# Compositor
# picom -b &

# Autokill
killall sxhkd; sxhkd &
killall dunst; dunst &
# pgrep -x sxhkd > /dev/null || sxhkd &
# pgrep -x dunst > /dev/null || dunst &

## Workspaces
bspc monitor -d 1 2 3 4 5 6

## Config
bspc config border_width          0
# bspc config window_gap            10
bspc config window_gap            0
bspc config border_radius         15
bspc config bottom_padding        0
bspc config split_ratio           0.5
bspc config normal_border_color   "#f7768e"
bspc config focused_border_color  "#353b45"

bspc config borderless_monocle    true
bspc config gapless_monocle       false 
bspc config focus_follows_pointer false
bspc config paddingless_monocle   true
bspc config single_monocle        false

bspc config automatic_scheme spiral       # Abrir janelas em espiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

## Rules
bspc rule -a feh state=floating
bspc rule -a Thunar state=floating focus=on
bspc rule -a nautilus state=floating focus=on
