#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          16
bspc config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5

bspc config automatic_scheme spiral       # Abrir janelas em espiral
bspc config initial_polarity first_child  # A janela que abrir sera sempre a primeira 
bspc config removal_adjustment true
bspc config split_ratio          0.5      # Proporcao da divisao quando abrir outra janela

bspc config normal_border_color "#000000"
bspc config focused_border_color "#ffffff"
bspc config focus_follows_pointer true
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a Firefox desktop='^1'
bspc rule -a Telegram desktop='^4' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#-----autostart-----
xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh &
$HOME/.config/polybar/launch.sh
$HOME/.fehbg
# $HOME/.config/polybar/launch.sh --forest
# wal -R
# picom -b
# feh --bg-fill ~/.dotfiles/wallpapers/wallpapper_space5.jpg
