#!/bin/sh

# sensors | grep 'CPU Temperature' | awk '{print substr($3, 2, length($3)-5)}' | tr "\\n" " " | sed 's/ /°C  /g' | sed 's/  $//'

sensors | grep 'Package id 0' | awk '{print $4}' | tr -d '+'
